# Generated by Django 5.1.6 on 2025-07-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('reviews', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
